# Generated by Django 5.2.9 on 2025-12-14 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='课程编号')),
                ('course_name', models.CharField(max_length=100, unique=True, verbose_name='课程名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='课程描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=10, verbose_name='性别')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级')),
                ('age', models.PositiveIntegerField(verbose_name='年龄')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='照片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='成绩ID')),
                ('score', models.FloatField(verbose_name='成绩')),
                ('exam_time', models.DateField(blank=True, null=True, verbose_name='考试时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.course', verbose_name='课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '成绩信息',
                'verbose_name_plural': '成绩信息',
                'db_table': 'score',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
